In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df_customers=pd.read_csv("Desktop/ECOMMERCE DATASET/ecommerce.customers.csv")
df_products=pd.read_csv("Desktop/ECOMMERCE DATASET/ecommerce_products.csv")
df_orders=pd.read_csv("Desktop/ECOMMERCE DATASET/ecommerce_orders.csv")

In [3]:
df_orders.head()

,order_id,customer_id,product_id,quantity,order_date,selling_price,order_value
0,ORD00001,CUST0166,PROD0016,3,2024-02-17,18883.28,56649.84
1,ORD00002,CUST0189,PROD0038,2,2024-01-29,3459.97,6919.94
2,ORD00003,CUST0078,PROD0046,2,2024-04-06,17595.60,35191.20
3,ORD00004,CUST0435,PROD0001,2,2024-01-10,16863.56,33727.12
4,ORD00005,CUST0090,PROD0049,4,2024-08-29,16903.09,67612.36

In [4]:
df_customers.head()

,customer_id,first_purchase_date,last_purchase_date,total_orders,total_spend
0,CUST0001,2024-04-12,2024-12-14,11,120395.08
1,CUST0002,2024-12-14,2025-08-28,3,85523.02
2,CUST0003,2024-09-27,2025-03-05,1,145619.66
3,CUST0004,2024-04-16,2025-03-21,6,18091.12
4,CUST0005,2024-03-12,2024-08-10,18,256397.09

In [5]:
df_products.head()

  product_id product_name     category  cost_price  selling_price   margin
0   PROD0001    Product_1       Health    12554.01       16863.56  4309.55
1   PROD0002    Product_2       Beauty     4915.85        7028.28  2112.43
2   PROD0003    Product_3      Fashion    14193.42       17896.94  3703.52
3   PROD0004    Product_4  Electronics    13226.71       15852.34  2625.63
4   PROD0005    Product_5       Health     3264.70        5415.33  2150.63

In [6]:
df = (
    df_orders
    .merge(df_customers, on="customer_id", how="left")
    .merge(df_products, on="product_id", how="left")
)

In [7]:
df.head()

,order_id,customer_id,product_id,quantity,order_date,selling_price_x,order_value,first_purchase_date,last_purchase_date,total_orders,total_spend,product_name,category,cost_price,selling_price_y,margin
0,ORD00001,CUST0166,PROD0016,3,2024-02-17,18883.28,56649.84,2024-04-17,2024-11-05,11,233862.40,Product_16,Health,11099.91,18883.28,7783.37
1,ORD00002,CUST0189,PROD0038,2,2024-01-29,3459.97,6919.94,2024-06-20,2024-10-19,16,284468.39,Product_38,Health,2704.67,3459.97,755.30
2,ORD00003,CUST0078,PROD0046,2,2024-04-06,17595.60,35191.20,2024-08-02,2024-12-23,15,256462.32,Product_46,Home,14110.29,17595.60,3485.31
3,ORD00004,CUST0435,PROD0001,2,2024-01-10,16863.56,33727.12,2024-10-01,2024-10-06,7,193205.64,Product_1,Health,12554.01,16863.56,4309.55
4,ORD00005,CUST0090,PROD0049,4,2024-08-29,16903.09,67612.36,2024-07-06,2025-01-07,10,5303.70,Product_49,Beauty,12920.28,16903.09,3982.81

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             4000 non-null   str
 1   customer_id          4000 non-null   str
 2   product_id           4000 non-null   str
 3   quantity             4000 non-null   int64
 4   order_date           4000 non-null   str
 5   selling_price_x      4000 non-null   float64
 6   order_value          4000 non-null   float64
 7   first_purchase_date  4000 non-null   str
 8   last_purchase_date   4000 non-null   str
 9   total_orders         4000 non-null   int64
 10  total_spend          4000 non-null   float64
 11  product_name         4000 non-null   str
 12  category             4000 non-null   str
 13  cost_price           4000 non-null   float64
 14  selling_price_y      4000 non-null   float64
 15  margin               4000 non-null   float64
dtypes: float64(6), int64(2), str(8)
memory usage: 774.7 KB

In [9]:
#Convert date column data type to datetime

df['order_date'] = pd.to_datetime(df['order_date'])
df['first_purchase_date'] = pd.to_datetime(df['first_purchase_date'])
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             4000 non-null   str
 1   customer_id          4000 non-null   str
 2   product_id           4000 non-null   str
 3   quantity             4000 non-null   int64
 4   order_date           4000 non-null   datetime64[us]
 5   selling_price_x      4000 non-null   float64
 6   order_value          4000 non-null   float64
 7   first_purchase_date  4000 non-null   datetime64[us]
 8   last_purchase_date   4000 non-null   datetime64[us]
 9   total_orders         4000 non-null   int64
 10  total_spend          4000 non-null   float64
 11  product_name         4000 non-null   str
 12  category             4000 non-null   str
 13  cost_price           4000 non-null   float64
 14  selling_price_y      4000 non-null   float64
 15  margin               4000 non-null   float64
dtypes: datetime64[us](3), float64(6), int64(2), str(5)
memory usage: 656.6 KB

In [11]:
# create one row customer level dataset
customer_df = df.groupby('customer_id').agg({
    'last_purchase_date':'max',
    'total_orders':'max',
    'total_spend':'max'
}).reset_index()

In [12]:
customer_df.head()

  customer_id last_purchase_date  total_orders  total_spend
0    CUST0001         2024-12-14            11    120395.08
1    CUST0002         2025-08-28             3     85523.02
2    CUST0003         2025-03-05             1    145619.66
3    CUST0004         2025-03-21             6     18091.12
4    CUST0005         2024-08-10            18    256397.09

In [13]:
# Calculate Recency i.e Number of days since last purchase
today = df['order_date'].max()

customer_df['recency'] = (today - customer_df['last_purchase_date']).dt.days

In [14]:
#  Define Recency & Monetary
customer_df['frequency'] = customer_df['total_orders']
customer_df['monetary'] = customer_df['total_spend']

Create RFM Scores

In [15]:
# Recency Score
customer_df['R_score'] = pd.qcut(customer_df['recency'], 5, labels=[5,4,3,2,1])

In [16]:
# Frequency Score
customer_df['F_score'] = pd.qcut(customer_df['frequency'].rank(method='first'),5,labels=[1,2,3,4,

_IncompleteInputError: incomplete input (1482493092.py, line 2)

In [ ]:
# Monetary Score
customer_df['M_score'] = pd.qcut(customer_df['monetary'],5,labels=[1,2,3,4,5])

In [ ]:
#Create RFM Segment
customer_df['RFM_score'] = (
    customer_df['R_score'].astype(str) +
    customer_df['F_score'].astype(str) +
    customer_df['M_score'].astype(str)
)

In [ ]:
# Assign Customer Segment
def segment(row):
    
    if row['R_score'] >= 4 and row['F_score'] >= 4:
        return "Loyal Customers"
    
    elif row['R_score'] >= 4 and row['F_score'] <= 2:
        return "New Customers"
    
    elif row['R_score'] <= 2 and row['F_score'] >= 4:
        return "At Risk"
    
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return "Lost Customers"
    
    else:
        return "Potential Loyalist"

customer_df['segment'] = customer_df.apply(segment, axis=1)

In [ ]:
# Analyze Segment
customer_df['segment'].value_counts()

DATA VISULIZATION

In [ ]:
segment_counts = customer_df['segment'].value_counts().reset_index()
segment_counts.columns = ['segment','count']

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import os

path = r"C:\Users\Dell\Desktop\customer_segmentation_charts.png"

fig, ax = plt.subplots(figsize=(12,6))

colors = ["#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd"]

bars = ax.bar(segment_counts['segment'], segment_counts['count'], color=colors)

ax.set_title("Customer Segmentation Distribution", fontsize=16, fontweight='bold')
ax.set_xlabel("Customer Segment")
ax.set_ylabel("Number of Customers")

plt.xticks(rotation=40)

for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x()+bar.get_width()/2, height+2, int(height), ha='center')

plt.tight_layout()

fig.savefig(path, dpi=300)

plt.show()